language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.2'

install:
  - composer install
  - ./vendor/bin/simple-phpunit install

script:
  - ./vendor/bin/simple-phpunit